Works without the string build to match on " 0." instead of "Failed: 0.". Try going for the "0, Skipped" earlier and extend to second file. Will still need to set a variable to true somehow so not out of the woods yet...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -42,10 +42,17 @@ script:
 after_success:
   # Run tests
   - dotnet test ./src/NetCoreXunit -xml ./out/NetCoreXunit.xml;
-    if ! grep -q ' 0.' ./out/NetCoreXunit.xml ;  then
+    if ! grep -q ' 0, SKipped' ./out/NetCoreXunit.xml ;  then
       echo 'Failed tests detected.';
+    else
+      echo 'All tests passed.';
     fi;
-  - dotnet test ./src/NetCoreXunitB -xml ./out/NetCoreXunitB.xml
+  - dotnet test ./src/NetCoreXunitB -xml ./out/NetCoreXunitB.xml;
+    if ! grep -q ' 0, SKipped' ./out/NetCoreXunitB.xml ;  then
+      echo 'Failed tests detected.';
+    else
+      echo 'All tests passed.';
+    fi;
   - dotnet test -help
 
   
