Tests are running but not breaking build; try pick up return code and see full cli help

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -42,3 +42,8 @@ after_success:
   - pushd src/NetCoreXunit && dotnet test && popd
   - cd ./src/NetCoreXunit
   - dotnet test
+  if [ $? -neq 0 ]; then
+    echo "Tests failed"
+    exit 1;
+  fi
+  - dotnet test -help
