fix error in yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,9 +41,9 @@ after_success:
   # Run tests
   - pushd src/NetCoreXunit && dotnet test && popd
   - cd ./src/NetCoreXunit
-  - dotnet test
-  if [ $? -neq 0 ]; then
-    echo "Tests failed"
-    exit 1;
-  fi
+  - dotnet test;
+    if [ $? -neq 0 ]; then
+      echo "Tests failed"
+      exit 1;
+    fi
   - dotnet test -help
